var members = [{
    'id': '12',// int(11) NOT NULL AUTO_INCREMENT,
    'nickname': 'Piet Jan',// varchar(255) NOT NULL,
    'firstname': 'Pietje',// varchar(255) NOT NULL,
    'infix': 'van',// varchar(255) DEFAULT NULL,
    'lastname': 'Pietersen',// varchar(255) NOT NULL,
    'street': 'Pietjanstraat',// varchar(255) DEFAULT NULL,
    'housenumber': '2',// varchar(255) DEFAULT NULL,
    'zipcode': '1234ab',// varchar(255) DEFAULT NULL,
    'city': 'Delft',// varchar(255) DEFAULT NULL,
    'country': 'Nieuw Amsterdam',// varchar(255) DEFAULT NULL,
    'gender': 'male',// enum('male','female') DEFAULT 'male',
    'email': 'piet@pietersen.pt',// varchar(255) DEFAULT NULL,
    'mobile': '01234123123',// varchar(255) DEFAULT NULL,
    'phone': '0123123123',// varchar(255) DEFAULT NULL,
    'iban': 'NL12NOBANK123123123123',// varchar(255) DEFAULT NULL,
    'birthdate': '2015-10-10',// date DEFAULT NULL,
    'deathdate': '2014-10-10',// date DEFAULT NULL,
    'emergencyinfo': 'Niet reanimeren?',// mediumtext,
    'membertype': 'member',// enum('member','exmember','donor','expelled') NOT NULL DEFAULT 'member',
    'membersince': '2014-10-10',// date DEFAULT NULL,
    'membertill': null,// date DEFAULT NULL,
    'functions': 'sudo',// mediumtext,
    'notes': '',// mediumtext,
    'wantscontact': 'yes',// enum('unknown','yes','no') NOT NULL DEFAULT 'yes',
    'keycode': '123123',// varchar(10) DEFAULT NULL,
    'coasters': true,// tinyint(1) NOT NULL DEFAULT '1',
    'cashregister': true,// tinyint(1) NOT NULL DEFAULT '1',
    'frontdoor': false,// tinyint(1) NOT NULL DEFAULT '0',
    'directdebit': 'contribution',// enum('no','contribution','contribution_coasters') NOT NULL DEFAULT 'contribution',
    'isadmin': false,// tinyint(1) NOT NULL DEFAULT '0',
    'passwordhash': 'hash?',// varchar(255) DEFAULT NULL,
    'modified': 'yesterday',// timestamp NULL DEFAULT NULL,
    'created': 'tomorrow'// timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
},{
    'id': '12',// int(11) NOT NULL AUTO_INCREMENT,
    'nickname': 'Piet Jan',// varchar(255) NOT NULL,
    'firstname': 'Pietje',// varchar(255) NOT NULL,
    'infix': 'van',// varchar(255) DEFAULT NULL,
    'lastname': 'Pietersen',// varchar(255) NOT NULL,
    'street': 'Pietjanstraat',// varchar(255) DEFAULT NULL,
    'housenumber': '2',// varchar(255) DEFAULT NULL,
    'zipcode': '1234ab',// varchar(255) DEFAULT NULL,
    'city': 'Delft',// varchar(255) DEFAULT NULL,
    'country': 'Nieuw Amsterdam',// varchar(255) DEFAULT NULL,
    'gender': 'male',// enum('male','female') DEFAULT 'male',
    'email': 'piet@pietersen.pt',// varchar(255) DEFAULT NULL,
    'mobile': '01234123123',// varchar(255) DEFAULT NULL,
    'phone': '0123123123',// varchar(255) DEFAULT NULL,
    'iban': 'NL12NOBANK123123123123',// varchar(255) DEFAULT NULL,
    'birthdate': '2015-10-10',// date DEFAULT NULL,
    'deathdate': '2014-10-10',// date DEFAULT NULL,
    'emergencyinfo': 'Niet reanimeren?',// mediumtext,
    'membertype': 'member',// enum('member','exmember','donor','expelled') NOT NULL DEFAULT 'member',
    'membersince': '2014-10-10',// date DEFAULT NULL,
    'membertill': null,// date DEFAULT NULL,
    'functions': 'sudo',// mediumtext,
    'notes': '',// mediumtext,
    'wantscontact': 'yes',// enum('unknown','yes','no') NOT NULL DEFAULT 'yes',
    'keycode': '123123',// varchar(10) DEFAULT NULL,
    'coasters': true,// tinyint(1) NOT NULL DEFAULT '1',
    'cashregister': true,// tinyint(1) NOT NULL DEFAULT '1',
    'frontdoor': false,// tinyint(1) NOT NULL DEFAULT '0',
    'directdebit': 'contribution',// enum('no','contribution','contribution_coasters') NOT NULL DEFAULT 'contribution',
    'isadmin': false,// tinyint(1) NOT NULL DEFAULT '0',
    'passwordhash': 'hash?',// varchar(255) DEFAULT NULL,
    'modified': 'yesterday',// timestamp NULL DEFAULT NULL,
    'created': 'tomorrow'// timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
},{
    'id': '12',// int(11) NOT NULL AUTO_INCREMENT,
    'nickname': 'Piet Jan',// varchar(255) NOT NULL,
    'firstname': 'Pietje',// varchar(255) NOT NULL,
    'infix': 'van',// varchar(255) DEFAULT NULL,
    'lastname': 'Pietersen',// varchar(255) NOT NULL,
    'street': 'Pietjanstraat',// varchar(255) DEFAULT NULL,
    'housenumber': '2',// varchar(255) DEFAULT NULL,
    'zipcode': '1234ab',// varchar(255) DEFAULT NULL,
    'city': 'Delft',// varchar(255) DEFAULT NULL,
    'country': 'Nieuw Amsterdam',// varchar(255) DEFAULT NULL,
    'gender': 'male',// enum('male','female') DEFAULT 'male',
    'email': 'piet@pietersen.pt',// varchar(255) DEFAULT NULL,
    'mobile': '01234123123',// varchar(255) DEFAULT NULL,
    'phone': '0123123123',// varchar(255) DEFAULT NULL,
    'iban': 'NL12NOBANK123123123123',// varchar(255) DEFAULT NULL,
    'birthdate': '2015-10-10',// date DEFAULT NULL,
    'deathdate': '2014-10-10',// date DEFAULT NULL,
    'emergencyinfo': 'Niet reanimeren?',// mediumtext,
    'membertype': 'member',// enum('member','exmember','donor','expelled') NOT NULL DEFAULT 'member',
    'membersince': '2014-10-10',// date DEFAULT NULL,
    'membertill': null,// date DEFAULT NULL,
    'functions': 'sudo',// mediumtext,
    'notes': '',// mediumtext,
    'wantscontact': 'yes',// enum('unknown','yes','no') NOT NULL DEFAULT 'yes',
    'keycode': '123123',// varchar(10) DEFAULT NULL,
    'coasters': true,// tinyint(1) NOT NULL DEFAULT '1',
    'cashregister': true,// tinyint(1) NOT NULL DEFAULT '1',
    'frontdoor': false,// tinyint(1) NOT NULL DEFAULT '0',
    'directdebit': 'contribution',// enum('no','contribution','contribution_coasters') NOT NULL DEFAULT 'contribution',
    'isadmin': false,// tinyint(1) NOT NULL DEFAULT '0',
    'passwordhash': 'hash?',// varchar(255) DEFAULT NULL,
    'modified': 'yesterday',// timestamp NULL DEFAULT NULL,
    'created': 'tomorrow'// timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
},{
    'id': '12',// int(11) NOT NULL AUTO_INCREMENT,
    'nickname': 'Piet Jan',// varchar(255) NOT NULL,
    'firstname': 'Pietje',// varchar(255) NOT NULL,
    'infix': 'van',// varchar(255) DEFAULT NULL,
    'lastname': 'Pietersen',// varchar(255) NOT NULL,
    'street': 'Pietjanstraat',// varchar(255) DEFAULT NULL,
    'housenumber': '2',// varchar(255) DEFAULT NULL,
    'zipcode': '1234ab',// varchar(255) DEFAULT NULL,
    'city': 'Delft',// varchar(255) DEFAULT NULL,
    'country': 'Nieuw Amsterdam',// varchar(255) DEFAULT NULL,
    'gender': 'male',// enum('male','female') DEFAULT 'male',
    'email': 'piet@pietersen.pt',// varchar(255) DEFAULT NULL,
    'mobile': '01234123123',// varchar(255) DEFAULT NULL,
    'phone': '0123123123',// varchar(255) DEFAULT NULL,
    'iban': 'NL12NOBANK123123123123',// varchar(255) DEFAULT NULL,
    'birthdate': '2015-10-10',// date DEFAULT NULL,
    'deathdate': '2014-10-10',// date DEFAULT NULL,
    'emergencyinfo': 'Niet reanimeren?',// mediumtext,
    'membertype': 'member',// enum('member','exmember','donor','expelled') NOT NULL DEFAULT 'member',
    'membersince': '2014-10-10',// date DEFAULT NULL,
    'membertill': null,// date DEFAULT NULL,
    'functions': 'sudo',// mediumtext,
    'notes': '',// mediumtext,
    'wantscontact': 'yes',// enum('unknown','yes','no') NOT NULL DEFAULT 'yes',
    'keycode': '123123',// varchar(10) DEFAULT NULL,
    'coasters': true,// tinyint(1) NOT NULL DEFAULT '1',
    'cashregister': true,// tinyint(1) NOT NULL DEFAULT '1',
    'frontdoor': false,// tinyint(1) NOT NULL DEFAULT '0',
    'directdebit': 'contribution',// enum('no','contribution','contribution_coasters') NOT NULL DEFAULT 'contribution',
    'isadmin': false,// tinyint(1) NOT NULL DEFAULT '0',
    'passwordhash': 'hash?',// varchar(255) DEFAULT NULL,
    'modified': 'yesterday',// timestamp NULL DEFAULT NULL,
    'created': 'tomorrow'// timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
},{
    'id': '12',// int(11) NOT NULL AUTO_INCREMENT,
    'nickname': 'Piet Jan',// varchar(255) NOT NULL,
    'firstname': 'Pietje',// varchar(255) NOT NULL,
    'infix': 'van',// varchar(255) DEFAULT NULL,
    'lastname': 'Pietersen',// varchar(255) NOT NULL,
    'street': 'Pietjanstraat',// varchar(255) DEFAULT NULL,
    'housenumber': '2',// varchar(255) DEFAULT NULL,
    'zipcode': '1234ab',// varchar(255) DEFAULT NULL,
    'city': 'Delft',// varchar(255) DEFAULT NULL,
    'country': 'Nieuw Amsterdam',// varchar(255) DEFAULT NULL,
    'gender': 'male',// enum('male','female') DEFAULT 'male',
    'email': 'piet@pietersen.pt',// varchar(255) DEFAULT NULL,
    'mobile': '01234123123',// varchar(255) DEFAULT NULL,
    'phone': '0123123123',// varchar(255) DEFAULT NULL,
    'iban': 'NL12NOBANK123123123123',// varchar(255) DEFAULT NULL,
    'birthdate': '2015-10-10',// date DEFAULT NULL,
    'deathdate': '2014-10-10',// date DEFAULT NULL,
    'emergencyinfo': 'Niet reanimeren?',// mediumtext,
    'membertype': 'member',// enum('member','exmember','donor','expelled') NOT NULL DEFAULT 'member',
    'membersince': '2014-10-10',// date DEFAULT NULL,
    'membertill': null,// date DEFAULT NULL,
    'functions': 'sudo',// mediumtext,
    'notes': '',// mediumtext,
    'wantscontact': 'yes',// enum('unknown','yes','no') NOT NULL DEFAULT 'yes',
    'keycode': '123123',// varchar(10) DEFAULT NULL,
    'coasters': true,// tinyint(1) NOT NULL DEFAULT '1',
    'cashregister': true,// tinyint(1) NOT NULL DEFAULT '1',
    'frontdoor': false,// tinyint(1) NOT NULL DEFAULT '0',
    'directdebit': 'contribution',// enum('no','contribution','contribution_coasters') NOT NULL DEFAULT 'contribution',
    'isadmin': false,// tinyint(1) NOT NULL DEFAULT '0',
    'passwordhash': 'hash?',// varchar(255) DEFAULT NULL,
    'modified': 'yesterday',// timestamp NULL DEFAULT NULL,
    'created': 'tomorrow'// timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
},{
    'id': '12',// int(11) NOT NULL AUTO_INCREMENT,
    'nickname': 'Piet Jan',// varchar(255) NOT NULL,
    'firstname': 'Pietje',// varchar(255) NOT NULL,
    'infix': 'van',// varchar(255) DEFAULT NULL,
    'lastname': 'Pietersen',// varchar(255) NOT NULL,
    'street': 'Pietjanstraat',// varchar(255) DEFAULT NULL,
    'housenumber': '2',// varchar(255) DEFAULT NULL,
    'zipcode': '1234ab',// varchar(255) DEFAULT NULL,
    'city': 'Delft',// varchar(255) DEFAULT NULL,
    'country': 'Nieuw Amsterdam',// varchar(255) DEFAULT NULL,
    'gender': 'male',// enum('male','female') DEFAULT 'male',
    'email': 'piet@pietersen.pt',// varchar(255) DEFAULT NULL,
    'mobile': '01234123123',// varchar(255) DEFAULT NULL,
    'phone': '0123123123',// varchar(255) DEFAULT NULL,
    'iban': 'NL12NOBANK123123123123',// varchar(255) DEFAULT NULL,
    'birthdate': '2015-10-10',// date DEFAULT NULL,
    'deathdate': '2014-10-10',// date DEFAULT NULL,
    'emergencyinfo': 'Niet reanimeren?',// mediumtext,
    'membertype': 'member',// enum('member','exmember','donor','expelled') NOT NULL DEFAULT 'member',
    'membersince': '2014-10-10',// date DEFAULT NULL,
    'membertill': null,// date DEFAULT NULL,
    'functions': 'sudo',// mediumtext,
    'notes': '',// mediumtext,
    'wantscontact': 'yes',// enum('unknown','yes','no') NOT NULL DEFAULT 'yes',
    'keycode': '123123',// varchar(10) DEFAULT NULL,
    'coasters': true,// tinyint(1) NOT NULL DEFAULT '1',
    'cashregister': true,// tinyint(1) NOT NULL DEFAULT '1',
    'frontdoor': false,// tinyint(1) NOT NULL DEFAULT '0',
    'directdebit': 'contribution',// enum('no','contribution','contribution_coasters') NOT NULL DEFAULT 'contribution',
    'isadmin': false,// tinyint(1) NOT NULL DEFAULT '0',
    'passwordhash': 'hash?',// varchar(255) DEFAULT NULL,
    'modified': 'yesterday',// timestamp NULL DEFAULT NULL,
    'created': 'tomorrow'// timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
},{
    'id': '12',// int(11) NOT NULL AUTO_INCREMENT,
    'nickname': 'Piet Jan',// varchar(255) NOT NULL,
    'firstname': 'Pietje',// varchar(255) NOT NULL,
    'infix': 'van',// varchar(255) DEFAULT NULL,
    'lastname': 'Pietersen',// varchar(255) NOT NULL,
    'street': 'Pietjanstraat',// varchar(255) DEFAULT NULL,
    'housenumber': '2',// varchar(255) DEFAULT NULL,
    'zipcode': '1234ab',// varchar(255) DEFAULT NULL,
    'city': 'Delft',// varchar(255) DEFAULT NULL,
    'country': 'Nieuw Amsterdam',// varchar(255) DEFAULT NULL,
    'gender': 'male',// enum('male','female') DEFAULT 'male',
    'email': 'piet@pietersen.pt',// varchar(255) DEFAULT NULL,
    'mobile': '01234123123',// varchar(255) DEFAULT NULL,
    'phone': '0123123123',// varchar(255) DEFAULT NULL,
    'iban': 'NL12NOBANK123123123123',// varchar(255) DEFAULT NULL,
    'birthdate': '2015-10-10',// date DEFAULT NULL,
    'deathdate': '2014-10-10',// date DEFAULT NULL,
    'emergencyinfo': 'Niet reanimeren?',// mediumtext,
    'membertype': 'member',// enum('member','exmember','donor','expelled') NOT NULL DEFAULT 'member',
    'membersince': '2014-10-10',// date DEFAULT NULL,
    'membertill': null,// date DEFAULT NULL,
    'functions': 'sudo',// mediumtext,
    'notes': '',// mediumtext,
    'wantscontact': 'yes',// enum('unknown','yes','no') NOT NULL DEFAULT 'yes',
    'keycode': '123123',// varchar(10) DEFAULT NULL,
    'coasters': true,// tinyint(1) NOT NULL DEFAULT '1',
    'cashregister': true,// tinyint(1) NOT NULL DEFAULT '1',
    'frontdoor': false,// tinyint(1) NOT NULL DEFAULT '0',
    'directdebit': 'contribution',// enum('no','contribution','contribution_coasters') NOT NULL DEFAULT 'contribution',
    'isadmin': false,// tinyint(1) NOT NULL DEFAULT '0',
    'passwordhash': 'hash?',// varchar(255) DEFAULT NULL,
    'modified': 'yesterday',// timestamp NULL DEFAULT NULL,
    'created': 'tomorrow'// timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
},{
    'id': '12',// int(11) NOT NULL AUTO_INCREMENT,
    'nickname': 'Piet Jan',// varchar(255) NOT NULL,
    'firstname': 'Pietje',// varchar(255) NOT NULL,
    'infix': 'van',// varchar(255) DEFAULT NULL,
    'lastname': 'Pietersen',// varchar(255) NOT NULL,
    'street': 'Pietjanstraat',// varchar(255) DEFAULT NULL,
    'housenumber': '2',// varchar(255) DEFAULT NULL,
    'zipcode': '1234ab',// varchar(255) DEFAULT NULL,
    'city': 'Delft',// varchar(255) DEFAULT NULL,
    'country': 'Nieuw Amsterdam',// varchar(255) DEFAULT NULL,
    'gender': 'male',// enum('male','female') DEFAULT 'male',
    'email': 'piet@pietersen.pt',// varchar(255) DEFAULT NULL,
    'mobile': '01234123123',// varchar(255) DEFAULT NULL,
    'phone': '0123123123',// varchar(255) DEFAULT NULL,
    'iban': 'NL12NOBANK123123123123',// varchar(255) DEFAULT NULL,
    'birthdate': '2015-10-10',// date DEFAULT NULL,
    'deathdate': '2014-10-10',// date DEFAULT NULL,
    'emergencyinfo': 'Niet reanimeren?',// mediumtext,
    'membertype': 'member',// enum('member','exmember','donor','expelled') NOT NULL DEFAULT 'member',
    'membersince': '2014-10-10',// date DEFAULT NULL,
    'membertill': null,// date DEFAULT NULL,
    'functions': 'sudo',// mediumtext,
    'notes': '',// mediumtext,
    'wantscontact': 'yes',// enum('unknown','yes','no') NOT NULL DEFAULT 'yes',
    'keycode': '123123',// varchar(10) DEFAULT NULL,
    'coasters': true,// tinyint(1) NOT NULL DEFAULT '1',
    'cashregister': true,// tinyint(1) NOT NULL DEFAULT '1',
    'frontdoor': false,// tinyint(1) NOT NULL DEFAULT '0',
    'directdebit': 'contribution',// enum('no','contribution','contribution_coasters') NOT NULL DEFAULT 'contribution',
    'isadmin': false,// tinyint(1) NOT NULL DEFAULT '0',
    'passwordhash': 'hash?',// varchar(255) DEFAULT NULL,
    'modified': 'yesterday',// timestamp NULL DEFAULT NULL,
    'created': 'tomorrow'// timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
},{
    'id': '12',// int(11) NOT NULL AUTO_INCREMENT,
    'nickname': 'Piet Jan',// varchar(255) NOT NULL,
    'firstname': 'Pietje',// varchar(255) NOT NULL,
    'infix': 'van',// varchar(255) DEFAULT NULL,
    'lastname': 'Pietersen',// varchar(255) NOT NULL,
    'street': 'Pietjanstraat',// varchar(255) DEFAULT NULL,
    'housenumber': '2',// varchar(255) DEFAULT NULL,
    'zipcode': '1234ab',// varchar(255) DEFAULT NULL,
    'city': 'Delft',// varchar(255) DEFAULT NULL,
    'country': 'Nieuw Amsterdam',// varchar(255) DEFAULT NULL,
    'gender': 'male',// enum('male','female') DEFAULT 'male',
    'email': 'piet@pietersen.pt',// varchar(255) DEFAULT NULL,
    'mobile': '01234123123',// varchar(255) DEFAULT NULL,
    'phone': '0123123123',// varchar(255) DEFAULT NULL,
    'iban': 'NL12NOBANK123123123123',// varchar(255) DEFAULT NULL,
    'birthdate': '2015-10-10',// date DEFAULT NULL,
    'deathdate': '2014-10-10',// date DEFAULT NULL,
    'emergencyinfo': 'Niet reanimeren?',// mediumtext,
    'membertype': 'member',// enum('member','exmember','donor','expelled') NOT NULL DEFAULT 'member',
    'membersince': '2014-10-10',// date DEFAULT NULL,
    'membertill': null,// date DEFAULT NULL,
    'functions': 'sudo',// mediumtext,
    'notes': '',// mediumtext,
    'wantscontact': 'yes',// enum('unknown','yes','no') NOT NULL DEFAULT 'yes',
    'keycode': '123123',// varchar(10) DEFAULT NULL,
    'coasters': true,// tinyint(1) NOT NULL DEFAULT '1',
    'cashregister': true,// tinyint(1) NOT NULL DEFAULT '1',
    'frontdoor': false,// tinyint(1) NOT NULL DEFAULT '0',
    'directdebit': 'contribution',// enum('no','contribution','contribution_coasters') NOT NULL DEFAULT 'contribution',
    'isadmin': false,// tinyint(1) NOT NULL DEFAULT '0',
    'passwordhash': 'hash?',// varchar(255) DEFAULT NULL,
    'modified': 'yesterday',// timestamp NULL DEFAULT NULL,
    'created': 'tomorrow'// timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
},{
    'id': '12',// int(11) NOT NULL AUTO_INCREMENT,
    'nickname': 'Piet Jan',// varchar(255) NOT NULL,
    'firstname': 'Pietje',// varchar(255) NOT NULL,
    'infix': 'van',// varchar(255) DEFAULT NULL,
    'lastname': 'Pietersen',// varchar(255) NOT NULL,
    'street': 'Pietjanstraat',// varchar(255) DEFAULT NULL,
    'housenumber': '2',// varchar(255) DEFAULT NULL,
    'zipcode': '1234ab',// varchar(255) DEFAULT NULL,
    'city': 'Delft',// varchar(255) DEFAULT NULL,
    'country': 'Nieuw Amsterdam',// varchar(255) DEFAULT NULL,
    'gender': 'male',// enum('male','female') DEFAULT 'male',
    'email': 'piet@pietersen.pt',// varchar(255) DEFAULT NULL,
    'mobile': '01234123123',// varchar(255) DEFAULT NULL,
    'phone': '0123123123',// varchar(255) DEFAULT NULL,
    'iban': 'NL12NOBANK123123123123',// varchar(255) DEFAULT NULL,
    'birthdate': '2015-10-10',// date DEFAULT NULL,
    'deathdate': '2014-10-10',// date DEFAULT NULL,
    'emergencyinfo': 'Niet reanimeren?',// mediumtext,
    'membertype': 'member',// enum('member','exmember','donor','expelled') NOT NULL DEFAULT 'member',
    'membersince': '2014-10-10',// date DEFAULT NULL,
    'membertill': null,// date DEFAULT NULL,
    'functions': 'sudo',// mediumtext,
    'notes': '',// mediumtext,
    'wantscontact': 'yes',// enum('unknown','yes','no') NOT NULL DEFAULT 'yes',
    'keycode': '123123',// varchar(10) DEFAULT NULL,
    'coasters': true,// tinyint(1) NOT NULL DEFAULT '1',
    'cashregister': true,// tinyint(1) NOT NULL DEFAULT '1',
    'frontdoor': false,// tinyint(1) NOT NULL DEFAULT '0',
    'directdebit': 'contribution',// enum('no','contribution','contribution_coasters') NOT NULL DEFAULT 'contribution',
    'isadmin': false,// tinyint(1) NOT NULL DEFAULT '0',
    'passwordhash': 'hash?',// varchar(255) DEFAULT NULL,
    'modified': 'yesterday',// timestamp NULL DEFAULT NULL,
    'created': 'tomorrow'// timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
},{
    'id': '12',// int(11) NOT NULL AUTO_INCREMENT,
    'nickname': 'Piet Jan',// varchar(255) NOT NULL,
    'firstname': 'Pietje',// varchar(255) NOT NULL,
    'infix': 'van',// varchar(255) DEFAULT NULL,
    'lastname': 'Pietersen',// varchar(255) NOT NULL,
    'street': 'Pietjanstraat',// varchar(255) DEFAULT NULL,
    'housenumber': '2',// varchar(255) DEFAULT NULL,
    'zipcode': '1234ab',// varchar(255) DEFAULT NULL,
    'city': 'Delft',// varchar(255) DEFAULT NULL,
    'country': 'Nieuw Amsterdam',// varchar(255) DEFAULT NULL,
    'gender': 'male',// enum('male','female') DEFAULT 'male',
    'email': 'piet@pietersen.pt',// varchar(255) DEFAULT NULL,
    'mobile': '01234123123',// varchar(255) DEFAULT NULL,
    'phone': '0123123123',// varchar(255) DEFAULT NULL,
    'iban': 'NL12NOBANK123123123123',// varchar(255) DEFAULT NULL,
    'birthdate': '2015-10-10',// date DEFAULT NULL,
    'deathdate': '2014-10-10',// date DEFAULT NULL,
    'emergencyinfo': 'Niet reanimeren?',// mediumtext,
    'membertype': 'member',// enum('member','exmember','donor','expelled') NOT NULL DEFAULT 'member',
    'membersince': '2014-10-10',// date DEFAULT NULL,
    'membertill': null,// date DEFAULT NULL,
    'functions': 'sudo',// mediumtext,
    'notes': '',// mediumtext,
    'wantscontact': 'yes',// enum('unknown','yes','no') NOT NULL DEFAULT 'yes',
    'keycode': '123123',// varchar(10) DEFAULT NULL,
    'coasters': true,// tinyint(1) NOT NULL DEFAULT '1',
    'cashregister': true,// tinyint(1) NOT NULL DEFAULT '1',
    'frontdoor': false,// tinyint(1) NOT NULL DEFAULT '0',
    'directdebit': 'contribution',// enum('no','contribution','contribution_coasters') NOT NULL DEFAULT 'contribution',
    'isadmin': false,// tinyint(1) NOT NULL DEFAULT '0',
    'passwordhash': 'hash?',// varchar(255) DEFAULT NULL,
    'modified': 'yesterday',// timestamp NULL DEFAULT NULL,
    'created': 'tomorrow'// timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
},{
    'id': '12',// int(11) NOT NULL AUTO_INCREMENT,
    'nickname': 'Piet Jan',// varchar(255) NOT NULL,
    'firstname': 'Pietje',// varchar(255) NOT NULL,
    'infix': 'van',// varchar(255) DEFAULT NULL,
    'lastname': 'Pietersen',// varchar(255) NOT NULL,
    'street': 'Pietjanstraat',// varchar(255) DEFAULT NULL,
    'housenumber': '2',// varchar(255) DEFAULT NULL,
    'zipcode': '1234ab',// varchar(255) DEFAULT NULL,
    'city': 'Delft',// varchar(255) DEFAULT NULL,
    'country': 'Nieuw Amsterdam',// varchar(255) DEFAULT NULL,
    'gender': 'male',// enum('male','female') DEFAULT 'male',
    'email': 'piet@pietersen.pt',// varchar(255) DEFAULT NULL,
    'mobile': '01234123123',// varchar(255) DEFAULT NULL,
    'phone': '0123123123',// varchar(255) DEFAULT NULL,
    'iban': 'NL12NOBANK123123123123',// varchar(255) DEFAULT NULL,
    'birthdate': '2015-10-10',// date DEFAULT NULL,
    'deathdate': '2014-10-10',// date DEFAULT NULL,
    'emergencyinfo': 'Niet reanimeren?',// mediumtext,
    'membertype': 'member',// enum('member','exmember','donor','expelled') NOT NULL DEFAULT 'member',
    'membersince': '2014-10-10',// date DEFAULT NULL,
    'membertill': null,// date DEFAULT NULL,
    'functions': 'sudo',// mediumtext,
    'notes': '',// mediumtext,
    'wantscontact': 'yes',// enum('unknown','yes','no') NOT NULL DEFAULT 'yes',
    'keycode': '123123',// varchar(10) DEFAULT NULL,
    'coasters': true,// tinyint(1) NOT NULL DEFAULT '1',
    'cashregister': true,// tinyint(1) NOT NULL DEFAULT '1',
    'frontdoor': false,// tinyint(1) NOT NULL DEFAULT '0',
    'directdebit': 'contribution',// enum('no','contribution','contribution_coasters') NOT NULL DEFAULT 'contribution',
    'isadmin': false,// tinyint(1) NOT NULL DEFAULT '0',
    'passwordhash': 'hash?',// varchar(255) DEFAULT NULL,
    'modified': 'yesterday',// timestamp NULL DEFAULT NULL,
    'created': 'tomorrow'// timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
}];
