


export default {
	AUTH_LOGIN_ERROR: "AUTH_LOGIN_ERROR",
	AUTH_LOGIN_REQUEST: "AUTH_LOGIN_REQUEST",
	AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
	AUTH_LOGOUT_REQUEST: "AUTH_LOGOUT_REQUEST",

	FIELDS_MOVE_SCHEMAFIELD: "FIELDS_MOVE_SCHEMAFIELD",
	FIELDS_CREATE_FIELDSET: "FIELDS_CREATE_FIELDSET",
	FIELDS_UPDATE_FIELD: "FIELDS_UPDATE_FIELD",

	GROUPS_UPDATE: "GROUPS_UPDATE",
	GROUPS_CREATE: "GROUPS_CREATE",

	PEOPLE_RECEIVE: "PEOPLE_RECEIVE",
	PEOPLE_UPDATE: "PEOPLE_UPDATE",
	PEOPLE_COMMIT: "PEOPLE_COMMIT",
	PEOPLE_CREATE: "PEOPLE_CREATE",

	PERMISSIONS_SET: "PERMISSIONS_SET"

}