


export default {
	AUTH_LOGIN_ERROR: "AUTH_LOGIN_ERROR",
	AUTH_LOGIN_REQUEST: "AUTH_LOGIN_REQUEST",
	AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
	AUTH_LOGOUT_REQUEST: "AUTH_LOGOUT_REQUEST",

	FIELDS_MOVE_SCHEMAFIELD: "FIELDS_MOVE_SCHEMAFIELD",
	FIELDS_CREATE_FIELDSET: "FIELDS_CREATE_FIELDSET",
	FIELDS_UPDATE_FIELD: "FIELDS_UPDATE_FIELD",

	GROUPS_UPDATE: "GROUPS_UPDATE",
	GROUPS_CREATE: "GROUPS_CREATE",

	MEMBERS_RECEIVE: "MEMBERS_RECEIVE",
	MEMBERS_UPDATE: "MEMBERS_UPDATE",
	MEMBERS_COMMIT: "MEMBERS_COMMIT",
	MEMBERS_CREATE: "MEMBERS_CREATE",

	PERMISSIONS_SET: "PERMISSIONS_SET"

}